export const LOGGED_IN_IS_LOADING = "LOGGED_IN_IS_LOADING";
export const LOGGED_IN_SUCCESS = "LOGGED_IN_SUCCESS";
export const LOGGED_IN_FAILURE = "LOGGED_IN_FAILURE";

export const SIGN_UP_IS_LOADING = "SIGN_UP_IS_LOADING";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const CONTACT_US_IS_LOADING = "CONTACT_US";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAILURE = "CONTACT_US_FAILURE";
