name : Firebase Deployment


on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deployment
    runs-on : ubuntu-latest

    steps:
      - name : get the source code
        uses: actions/checkout@master

      - name : install node
        uses: actions/setup-node@master
        with:
            node-version: '14'

      - name : install node packages
        run: npm i
                  
      - name: Build
        run: npm run build
        env:
          CI: false
      
      - name : Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

